### ISSUE TITLE
Responsive menu not working

### ISSUE THREAD

**Issue by ninia-o** [weDevsOfficial/dokani#21]
A menu is already set and defined in the Responsive menu location but when you view the site on a phone or i[pad (and even on previewer), the responsive menu sandwich shows "Add Responsive menu" when clicked.

**Comment by insxa** [comment]
also for me. can you fix this ?

**Comment by AntHab** [comment]
Same here ... Hidden looks better.

**Comment by nurul-umbhiya** [comment]
Fixed
