### ISSUE TITLE
(dokani) contains outdated copies of some WooCommerce template files

### ISSUE THREAD

**Issue by ninia-o** [weDevsOfficial/dokani#22]
dokani-develop/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 4.0.0,

**Comment by insxa** [comment]
i copied from woocommerce, that solves or you can make it fixed?

**Comment by Xyala** [comment]
Hi all, is there a fix to this that is in the works ?

We are trying out the template for an upcoming marketplace site, but we'd love to have an up to date version before going into production. Thanks!

There are two issues actually:
- dokani-develop/woocommerce/cart/mini-cart.php version 3.7.0 is out of date. The core version is 5.2.0
- dokani-develop/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 4.0.0,

**Comment by Mojazteo** [comment]
Same problems still exists as of November 4, 2021. Are you going to update soon? Or should I try to update myself using a child theme? 

1.dokani-develop/woocommerce/cart/mini-cart.php version 3.7.0 is out of date. The core version is 5.2.0

2. dokani-develop/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 4.0.0,

**Comment by AntHab** [comment]
I wish I know how to fix that ... Suggestions? Ty.
