### ISSUE TITLE
Email address is showing although email checkbox is disable from vendor settings

### ISSUE THREAD

**Issue by shahadat015** [weDevsOfficial/dokani#30]
Describe the bug:
Email address is showing on the store although Show email address in-store checkbox is unchecked from vendor store settings

How to Reproduce:
1. Go to vendor dashboard.
2. Click on settings.
2. Disable email checkbox.

Attachment:
Video link: https://www.loom.com/share/e8670ca189bd4295b47bbbb0cf552225

Expected Result: Email address will not be showing
Actual Result: Showing email address in-store

Bug Type: Functional
Dokan Version: 3.2.11
Dokan Pro: Deactivate
WooCommerce Version: 5.6.0
Browser: Chrome, Firefox

**Comment by AntHab** [comment]
Email is still showing ... any help ? Thank you.
