### ISSUE TITLE
Function Prefix

### ISSUE THREAD

**Issue by saimonh3** [weDevsOfficial/dokani#6]
1. Prefix should be **dokanee** instead of **dokani**.
2. GENERATE_VERSION is so generic. Prefix should be added.

![Screen Shot 2019-11-21 at 8 36 58 PM](https://user-images.githubusercontent.com/13016829/69348115-d7518a00-0c9f-11ea-8adb-56a21cbc3637.png)

**Comment by ahsanshaheen199** [comment]
It has been fixed at #45
